// <auto-generated />
namespace TeamJAMiN.DataContexts.GalleristComponentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GameActionIds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameActionIds));
        
        string IMigrationMetadata.Id
        {
            get { return "201606030016174_GameActionIds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
