// <auto-generated />
namespace TeamJAMiN.DataContexts.GalleristComponentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExecutiveStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExecutiveStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201608201414073_ExecutiveStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
